### ISSUE TITLE
Sunrise/Sunset time are incorrect

### ISSUE THREAD

**Issue by bleomycin** [johnwargo/raspberry-pi-relay-timer#1]
First, thank you for creating this. It is exactly what I need and I can see a ton of work went into it. I'm planning to use it to control a solar powered fan in a greenhouse. (Unrelated to this problem, but I noticed offset times are limited to 60 minutes. How bad of an idea is it to set an offset time of 270 minutes? I don't need my fan starting up until around 10:30am).

For some reason the software seems to be pulling incorrect sunrise/sunset data for my timezone.

I have input:

```
LOC_LAT = "33.5973864"
LOC_LONG = "-117.8369007"
```

However on controller.py startup the output is:

```
Requesting solar data from http://api.sunrise-sunset.org/json
Sunrise: 508
Sunset: 1841
```
This appears to be wrong. Sunset time for today was actually 19:34, and sunrise 6:02 according to sunrise-sunset.org.
```
timedatectl
  Local time: Sun 2017-04-30 19:23:59 PDT
  Universal time: Mon 2017-05-01 02:23:59 UTC
       RTC time: n/a
       Time zone: America/Los_Angeles (PDT, -0700)
     NTP enabled: no
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2017-03-12 01:59:59 PST
                  Sun 2017-03-12 03:00:00 PDT
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2017-11-05 01:59:59 PDT
                  Sun 2017-11-05 01:00:00 PST
```
```
python -V
Python 2.7.9
```

Please let me know if there is anything else I can provide, I'm running current raspbian jessie lite on a pi zero w.

**Comment by johnwargo** [comment]
@bleomycin I'm sorry, for some reason I wasn't notified that this issue was here. I'm so sorry for the late reply.  Yeah, I limited the offset time to 60 minutes to make the code easier to write, dealing with an offset greater than an hour increased the complexity of the code and I was in a hurry to get it done. I've heard from another hobbyist who had the same issue, so perhaps I'll revisit that code and enhance it to support any offset. 

Regarding solar times calculation, I'm not sure what's happening there - all I'm doing is asking the web service for the data, converting it to local timezone and working with it as is. It's possible that the conversion isn't working correctly, but that's not my code, I'm merely adding a timezone to the value returned by the service and using converting that value to local time.  This other user expressed the same concern so I'm working with him to see if I can sort it out. I'll publish an update if I do.
